version: '3.8'

services:
  onnx-api:
    container_name: onnx-api
    build:
      context: ./onnx
      dockerfile: onnx.dockerfile
    ports:
      - "8001:8000"
    networks:
      api-network:
        ipv4_address: 192.168.10.2
    hostname: onnxapi
    command: "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 600 --access-logfile -"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 2s
      retries: 10
      start_period: 15s

  pytorch-api:
    container_name: pytorch-api
    build:
      context: ./pytorch
      dockerfile: pytorch.dockerfile
    ports:
      - "8002:8000"
    networks:
      api-network:
        ipv4_address: 192.168.10.3
    hostname: pytorchapi
    command: "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 600 --access-logfile -"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 2s
      retries: 10
      start_period: 15s

  tensorflow-api:
    container_name: tensorflow-api
    build:
      context: ./tensorflow
      dockerfile: tensorflow.dockerfile
    ports:
      - "8003:8000"
    networks:
      api-network:
        ipv4_address: 192.168.10.4
    hostname: tensorflowapi
    command: "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 600 --access-logfile -"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 15s

  benchmark:
    container_name: benchmark
    build:
      context: ./benchmark
      dockerfile: benchmark.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./benchmark/data:/app/data
      - ./benchmark/results:/app/results
    depends_on:
      onnx-api:
        condition: service_healthy
      pytorch-api:
        condition: service_healthy
      tensorflow-api:
        condition: service_healthy
    command: python main.py
    networks:
      api-network:
        ipv4_address: 192.168.10.5
  
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    tty: true  # Keep the container running
    stdin_open: true  # Allows interactive mode
    command: >
      bash -c "apt-get update && apt-get install -y iputils-ping curl && bash"
    networks:
      api-network:
        ipv4_address: 192.168.10.10


networks:
  api-network:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
